#:schema node_modules/wrangler/config-schema.json
name = "monarv"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "26b06e79780c4c75890bd2deabb9335a" }
]
